language: php
php: '5.5'

before_install:
  - openssl aes-256-cbc -K $encrypted_063d800574c6_key -iv $encrypted_063d800574c6_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d

install:
  - composer self-update
  - composer config -g github-oauth.github.com $GITHUB_API_TOKEN
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs --report=summary -np .
  - ./vendor/bin/phpunit --testsuite unit

deploy:
  provider: script
  script: bin/deploy
  on:
    branch: develop
