language: php
php: '5.5'

install:
  - composer self-update
  - composer config -g github-oauth.github.com $GITHUB_API_TOKEN
  - composer install --no-interaction

script:
  - ./vendor/bin/phpcs --report=summary -np .
  - ./vendor/bin/phpunit --testsuite unit
