language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - composer config -g github-oauth.github.com $GITHUB_API_TOKEN
  - composer install --no-interaction

script: ./vendor/bin/phpcs --report=summary -n .
