version: '3'
services:
  web:
    build:
      context: ./
      args:
        - NPM_CONFIG_ENVATO_TOKEN
    image: phototech/sailvenice
    env_file:
      - .env
    links:
      - database
    volumes:
      - ./config:/var/www/config:cached
      - ./html/sites/default:/var/www/html/sites/default:cached
      - ./html/themes:/var/www/html/themes:cached
      - ./html/modules:/var/www/html/modules:cached
  cache:
    image: phototech/varnish
    ports:
      - 8888:80
    links:
      - web:backend
  database:
    image: mariadb:10.3
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
