version: '3'
services:
  web:
    build:
      context: ./
      args:
        - NPM_CONFIG_ENVATO_TOKEN
    image: phototech/sailvenice
    env_file:
      - .env
    volumes:
      - ./html/sites/default:/var/www/html/sites/default:cached
  cache:
    image: davidbarratt/varnish
    ports:
      - 8888:80
    links:
      - web:backend
  cron:
    image: davidbarratt/cron
    env_file:
      - .env
    links:
      - web
