version: '3'
services:
  web:
    restart: always
    networks:
      - default
      - database
  cache:
    restart: always
    networks:
      - default
      - ingress
  cron:
    restart: always
networks:
  ingress:
    external:
      name: ingress
  database:
    external:
      name: database
