version: '3'
services:
  web:
    build:
      context: ./
      args:
        - NPM_CONFIG_ENVATO_TOKEN
    image: docker.davidwbarratt.com/phototech/sailvenice
    env_file:
      - .env
    volumes:
      - files:/var/www/html/sites/default/files
      - tmp:/var/www/tmp
  cache:
    image: davidbarratt/varnish
    environment:
      VIRTUAL_HOST: sailvenice.com,origin.sailvenice.com,www.sailvenice.com
      LETSENCRYPT_HOST: sailvenice.com,origin.sailvenice.com,www.sailvenice.com
    links:
      - web:backend
  cron:
    image: davidbarratt/cron
    env_file:
      - .env
    links:
      - web
volumes:
  files:
  tmp:
