id: seven_page_title
region: header
plugin: page_title_block
settings:
  label: 'Page title'
  label_display: '0'
visibility: {  }
weight: -50
langcode: en
uuid: 09853056-257a-4c78-b300-d15ba6532726
theme: seven
dependencies:
  theme:
    - seven
