plugin: local_tasks_block
region: pre_content
id: seven_secondary_local_tasks
settings:
  label: 'Secondary tabs'
  label_display: '0'
  primary: false
  secondary: true
visibility: {  }
weight: 0
langcode: en
uuid: 87fbf845-1251-432f-bc41-6577bc9d4686
theme: seven
dependencies:
  theme:
    - seven
