id: classy_page_title
region: content
plugin: page_title_block
settings:
  label: 'Page title'
  label_display: '0'
visibility: {  }
weight: -50
langcode: en
uuid: 64482218-29f1-4467-9509-9a823b433963
theme: classy
dependencies:
  theme:
    - classy
