module:
  address: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  contact: 0
  contact_link: 0
  contact_storage: 0
  contextual: 0
  datetime: 0
  dblog: 0
  display_field_copy: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  imagemagick: 0
  layout_plugin: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  name: 0
  node: 0
  options: 0
  paragraphs: 0
  path: 0
  purge: 0
  purge_processor_lateruntime: 0
  purge_purger_http: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  rdf: 0
  search: 0
  simple_gmap: 0
  stage_file_proxy: 0
  system: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  ds: 1
  minimal: 1000
theme:
  classy: 0
  seven: 0
  stable: 0
  sailor: 0
