module:
  block: 0
  breakpoint: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  layout_plugin: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  ds: 1
  minimal: 1000
theme:
  classy: 0
  seven: 0
  stable: 0
  sailor: 0
