id: contact_small
label: 'Contact (Small)'
ui_limit: 'services|*'
properties:
  block: 'block_content:19fb2cf0-19e2-42f8-92e1-736a06554c00'
  use_block_title: true
type: block
type_label: 'Block field'
entities:
  node: node
